---
- name: Install python3-selinux
  become: true
  ansible.builtin.package:
    name: "{{ python_selinux[ansible_os_family] }}"
    state: present

- name: Install Vagrant public SSH key
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    key: https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
