---
- name: Install python3-selinux
  apt:
    name: python3-selinux
    state: present

- name: Install Vagrant public SSH key
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    key: https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
