galaxy_info:
  role_name: vbox_guest
  author: Eugene Zamriy
  description: Installs VirtualBox Guest Additions
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 8
  galaxy_tags:
    - guest
    - system
    - virtualbox

dependencies: []
