#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    username: vagrant
    password: "vagrant"
  keyboard:
    layout: us
  locale: en_US
  network:
    network:
      version: 2
      ethernets:
        eth0:
          dhcp4: true
  storage:
    layout:
      name: lvm
    swap:
      size: 512MiB
    config:
      - id: disk0
        type: disk
        size: 100%
        match:
          size: 100000000000
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        path: /dev/sda
        part:
          - id: part1
            size: 1MiB
            type: bios_grub
            format: none
          - id: part2
            size: 200MiB
            type: fat32
            format: fat32
            mount: /boot/efi
          - id: part3
            size: 512MiB
            type: xfs
            format: xfs
            mount: /boot
          - id: part4
            size: 100%
            type: xfs
            format: xfs
            mount: /
  packages:
    - openssh-server
    - grub2
  user-data:
    disable_root: false
    ssh:
      install-server: true
      allow-pw: true
  late-commands:
    - echo "vagrant:vagrant" | chpasswd
    - echo "vagrant ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/vagrant
    - sed -i "s/^.*requiretty/# Defaults requiretty/" /etc/sudoers
    - timedatectl set-local-rtc 0
  # Additional configurations can be added here
  timezone: UTC
  # Disable kdump (if needed)
  kdump:
    enable: false
