---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: centos-8
    box: centos/8
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint

scenario:
  name: default
  test_sequence:
    #- dependency
    - lint
    #- cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    #- side_effect
    - verify
    #- cleanup
    - destroy
