---

# An Ansible playbook that configures a Vagrant box


- name: "AlmaLinux Vagrant Box"
  hosts: default
  become: true

  collections:
    - almalinux.ci

  roles:
    - role: unified_boot
      when: is_unified_boot is defined
    - role: philnewm.vbox_guest
      vbox_guest_state: "present"
      when: packer_provider == "virtualbox-iso"
    - role: qemu_guest
      when: packer_provider == "qemu"
    - role: philnewm.vagrant_box_prep
      vagrant_box_prep_state: "present"
    - role: philnewm.gnome
      gnome_setup_state: present
      gnome_enable_reboot: true
    - role: cleanup_vm
      cleanup_ssh_host_keys: "{{ packer_provider != 'hyperv-iso' }}"

...
