---

# An Ansible playbook that configures a Vagrant box


- name: "AlmaLinux Vagrant Box"
  hosts: default
  become: true
  collections:
    - almalinux.ci

  roles:
    - role: unified_boot
      when: is_unified_boot is defined
    - role: ezamriy.vbox_guest
      when: packer_provider == 'virtualbox-iso'
    - role: qemu_guest
      when: packer_provider == 'qemu'
    - install_vagrant_key
    - nfs-client
    - role: philnewm.gnome
      gnome_setup_state: present
      gnome_enable_reboot: false
    - role: cleanup_vm
      cleanup_ssh_host_keys: "{{ packer_provider != 'hyperv-iso' }}"

...
