---

# An Ansible playbook that configures a Vagrant box


- name: "AlmaLinux Vagrant Box"
  hosts: default
  become: true
  collections:
    - almalinux.ci

  roles:
    - upgrade_and_reboot
    - ezamriy.vbox_guest
    - install_vagrant_key
    - nfs-client
    - role: philnewm.gnome
      gnome_setup_state: present
    - role: cleanup_vm
      cleanup_ssh_host_keys: "{{ packer_provider != 'hyperv-iso' }}"
