---

name: alma9-qemu-ci

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  #   paths-ignore:
  #     - 'README.md'
  #     - 'TODO.md'
  #     - '**/*.md'
  #     - .gitignore

  # pull_request:
  #   branches: [ "main" ]
  #   paths-ignore:
  #       - 'README.md'
  #       - '**/*.md'
  #       - .gitignore

permissions:
  contents: read

jobs:
  alma9-qemu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo  
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install vagrant
        run: |
          # Get vagrant gpg key
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install vagrant -y

      - name: Verify Vagrant installation
        run: vagrant --version

      - name: Install qemu
        run: |
          sudo apt-get update
          sudo apt-get install rsync
          sudo apt-get install -y qemu qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils libvirt-dev
          sudo systemctl enable --now libvirtd
          sudo usermod -aG libvirt $(whoami)

      - name: Install libvirt vagrant plugin
        run: |
          vagrant plugin install vagrant-libvirt

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3.1.0
        id: setup

      - name: Verify packer installation
        run: packer --version

      # TODO RnD dynamic way to do this - ideally inside the packer vars
      - name: Set qemu_binary path
        run: |
          export PKR_VAR_qemu_binary="/usr/bin/qemu-system-x86_64"

      - name: Run packer build
        run: |
          packer init versions.pkr.hcl
          packer build -only=qemu.almalinux-9 .

      - name: Test to run vagrant box
        run: |
          vagrant box add --name alma9 --provider=libvirt AlmaLinux-9-Vagrant-qemu-9.4.x86_64.box
          rm Vagrantfile
          vagrant init alma9
          vagrant up --provider=libvirt

      - name: Upload vagrant box
        uses: actions/upload-artifact@v4
        with:
          name: alma9-qemu-vagrant-box
          path: AlmaLinux-9-Vagrant-qemu-9.4.x86_64.box

...